version: "3.9"

services:
  db:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_DB: django_db
      POSTGRES_USER: django_user
      POSTGRES_PASSWORD: django_password
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  web:
    build: .
    command:
      - sh
      - -c
      - |
        python manage.py migrate &&
        python manage.py collectstatic --noinput &&
        gunicorn django_lms.wsgi:application --bind 0.0.0.0:8000 --workers 3
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DB_NAME: django_db
      DB_USER: django_user
      DB_PASSWORD: django_password
      DB_HOST: db
      DB_PORT: 5432
      SECRET_KEY: super-secret-key
      DEBUG: "False"
      ALLOWED_HOSTS: "*"

volumes:
  postgres_data: