services:
  db:
    image: postgres:17
    restart: always
    volumes:
       - postgres_data:/var/lib/postgresql/data/
    environment:
        - POSTGRES_DB=django_db
        - POSTGRES_USER=django_user
        - POSTGRES_PASSWORD=django_password
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U django_user -d django_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build: .
    restart: always
    command: >
      sh -c "python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             gunicorn django_lms.wsgi:application --bind 0.0.0.0:8000 --workers 3 --timeout 120"
    volumes:
      - .:/app
    ports:
      - "0.0.0.0:8000:8000"
    environment:
      - DB_NAME=django_db
      - DB_USER=django_user
      - DB_PASSWORD=django_password
      - DB_HOST=db
      - DB_PORT=5432
      - ALLOWED_HOSTS=*
      - DEBUG=False
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data:
